version: '2'
services:
  runner:
   image: api_runner
   links:
    - server:oasis_api_server
  server:
   image: oasis_api_server
   ports:
     - "8001:80"
   environment:
     - RABBIT_PORT=5672
     - MYSQL_PORT=3306
   volumes:
#     - ./log:/var/log/oasis:rw
     - ./upload:/var/www/oasis/upload:rw
     - ./download:/var/www/oasis/download:rw
  worker1:
    image: model_execution_worker
    environment:
     - OASIS_MODEL_SUPPLIER_ID=OasisIM
     - OASIS_MODEL_VERSION_ID=1
     - OASIS_RABBIT_PORT=5672
     - OASIS_MYSQL_PORT=3306
     - OASIS_LOCK_FILE=/tmp/tmp_ktools_lock_file_1
     - OASIS_DO_CLEAR_WORKING=True
     - OASIS_KTOOLS_BATCH_COUNT=-1
     - OASIS_LOCK_RETRY_COUNTDOWN_IN_SECS=10
     - OASIS_LOCK_TIMEOUT_IN_SECS=10
     - OASIS_LOG_LEVEL=DEBUG
     - OASIS_POST_ANALYSIS_SLEEP_IN_SECS=10
    volumes:  
#     - ./log:/var/log/oasis:rw
     - /tmp:/tmp
     - ./upload:/var/www/oasis/upload:rw
     - ./download:/var/www/oasis/download:rw
     - ./data/static:/var/oasis/model_data/OasisIM/1:rw
  worker2:
    image: model_execution_worker
    environment:
     - OASIS_MODEL_SUPPLIER_ID=OasisIM
     - OASIS_MODEL_VERSION_ID=1
     - OASIS_RABBIT_PORT=5672
     - OASIS_MYSQL_PORT=3306
     - OASIS_LOCK_FILE=/tmp/tmp_ktools_lock_file_1
     - OASIS_DO_CLEAR_WORKING=True
     - OASIS_KTOOLS_BATCH_COUNT=-1
     - OASIS_LOCK_TIMEOUT_IN_SECS=10
     - OASIS_LOCK_RETRY_COUNTDOWN_IN_SECS=5
     - OASIS_LOG_LEVEL=DEBUG
     - OASIS_POST_ANALYSIS_SLEEP_IN_SECS=10     
    volumes:
#     - ./log:/var/log/oasis:rw
     - /tmp:/tmp
     - ./upload:/var/www/oasis/upload:rw
     - ./download:/var/www/oasis/download:rw
     - ./data/static:/var/oasis/model_data/OasisIM/2:rw
  oasis_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery 
  oasis_rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"


