FROM ubuntu:18.04

COPY ./apt.txt ./
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y $(grep -vE "^\s*#" apt.txt  | tr "\n" " ") && \
    apt-get install -y python3.6 python3-pip && \
    rm -rf /var/lib/apt/lists/*

ARG BRANCH=develop
RUN /bin/bash -c "pip3 install git+{https,ssh}://git@github.com/OasisLMF/OasisLMF.git@${BRANCH}#egg=oasislmf"
