FROM ubuntu:18.04

COPY ./apt.txt ./
RUN apt update && \
    apt upgrade -y && \
    apt install -y $(grep -vE "^\s*#" apt.txt  | tr "\n" " ") && \
    rm -rf /var/lib/apt/lists/*

RUN pip install git+{https,ssh}://git@github.com/OasisLMF/OasisLMF_SQL.git@master#egg=oasislmf 
